### ISSUE TITLE
希望增加切换cookie功能

### ISSUE THREAD

**Issue by kerncoola** [yann0917/dedao-dl#1]
另外麻烦大佬说下cookie的格式，即dedao-dl login -c XXX

**Comment by kerncoola** [comment]
![image](https://user-images.githubusercontent.com/13283995/104170190-b0be5780-543b-11eb-89a6-0491d16ac699.png)
![image](https://user-images.githubusercontent.com/13283995/104170233-c3d12780-543b-11eb-97b9-bf8002befaca.png)

**Comment by yann0917** [comment]
> 另外麻烦大佬说下cookie的格式，即dedao-dl login -c XXX

就是请求头里的整个 Coookies  值, 另: cookie 里有空格，记得用双引号引起来。

**Comment by kerncoola** [comment]
![image](https://user-images.githubusercontent.com/13283995/104182020-c129fe80-544a-11eb-9336-4fab264e6e95.png)

**Comment by kerncoola** [comment]
不知道是不是我理解错了，总是登录不上

**Comment by yann0917** [comment]
> 不知道是不是我理解错了，总是登录不上

增加了切换账号功能，拉取最新代码试用一下。

**Comment by kerncoola** [comment]
感谢大佬

**Comment by newdhl** [comment]
大佬，新年好，我是一个没编过程的小白，一天探索研究能把go的环境都弄好走到运行到登录这一步已经用尽全力了，但是卡在登录这一步，看了上面的这一段还是不明白，还是不知道login -c 后面引号中要怎么写，也不知道"请求头里的整个 Coookies 值"要怎么弄，求助一个步骤，万分感谢！

**Comment by yann0917** [comment]
> 大佬，新年好，我是一个没编过程的小白，一天探索研究能把go的环境都弄好走到运行到登录这一步已经用尽全力了，但是卡在登录这一步，看了上面的这一段还是不明白，还是不知道login -c 后面引号中要怎么写，也不知道"请求头里的整个 Coookies 值"要怎么弄，求助一个步骤，万分感谢！

1. 登录网页版得到 https://www.dedao.cn
2. 浏览器打开调试模式（按F12），切换到网络(network)栏
3. 随便打开一个 https://www.dedao.cn 开头的请求 ，就能看到请求头的 Cookie 值
4. 执行 dedao-dl login -c "xxx" （xxx 换成 cookie）即可

**Comment by newdhl** [comment]
> 

登录成功了！非常感谢

还有一个问题，course  odob cat等命令用起来都没问题，但是dl下载失败，确认了course id没写错，而且 -t 后1  2  3 都不行，如
C:\Users\Y>dedao-dl dl 390 -t 1
Error: open ./.cache/articleList:pg2x7w4mGy0Xm1pHMvXkbP631aWeBz::0: The filename, directory name, or volume label syntax is incorrect.

我这里的390是潇雨个人投资课，和您例子中的51代码不同，如果用51，说我没购买这个课程。

试了dedao-dl dl 123 -t 1  （123这个课我也买了），但是也提示下载错误
C:\Users\Y>dedao-dl dl 123 -t 1
Error: open ./.cache/articleList:OY8PNZj5EavJq1aHpPJn1eqGDdlgw7::0: The filename, directory name, or volume label syntax is incorrect.

麻烦大佬有空的时候看看，谢谢！
