### ISSUE TITLE
已购课程share

### ISSUE THREAD

**Issue by kerncoola** [yann0917/dedao-dl#119]
自购了一些课程，看看有没有需要的。

直接给账号登录APP，不收费。

![image](https://user-images.githubusercontent.com/13283995/186880638-be75948d-7809-46fd-bb9e-891e7515bed2.png)

![IMG_3843](https://user-images.githubusercontent.com/13283995/186880317-561c6eda-a428-42af-8fa8-3d96b5cd9d92.JPEG)

**Comment by fa0773** [comment]
过期了二维码：（
