### ISSUE TITLE
能否增加电子书下载为md格式的选项

### ISSUE THREAD

**Issue by xukai504087493** [yann0917/dedao-dl#132]
建议增加电子书的md格式，默认的html格式没有目录结构。
我看到下载电子书的过程中，有输出章节信息的。
是否可以将这些章节目录添加到md文件里，这样子看书会更加方便（有目录结构的书，阅读起来会更方便）。
如果增加了，还请发布到新release版本里，谢谢您。

**Comment by yann0917** [comment]
电子书没法转 md 格式的

**Comment by xukai504087493** [comment]
电子书目录信息能否添加到电子书里呢？电子书页面是有完整的目录结构的。如下图：
<img width="432" alt="image" src="https://user-images.githubusercontent.com/6873069/194190233-04560c4a-7fa5-4230-a470-f58e85a4d926.png">
