### ISSUE TITLE
docker login -c  <panic: runtime error: invalid memory address or nil pointer dereference>

### ISSUE THREAD

**Issue by smartlin** [yann0917/dedao-dl#136]
docker 运行登录的时，出现如下错误:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa01011]

goroutine 1 [running]:
github.com/yann0917/dedao-dl/cmd.who()
	/build/cmd/login.go:110 +0xd1
github.com/yann0917/dedao-dl/cmd.glob..func11(0x1188720?, {0xb38709?, 0x2?, 0x2?})
	/build/cmd/login.go:44 +0x17
github.com/spf13/cobra.(*Command).execute(0x1188720, {0xc000072de0, 0x2, 0x2})
	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:883 +0x6d0
github.com/spf13/cobra.(*Command).ExecuteC(0x11889a0)
	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
github.com/yann0917/dedao-dl/cmd.Execute(...)
	/build/cmd/root.go:29
main.main()
	/build/main.go:17 +0x25
```

**Comment by yann0917** [comment]
请使用 login -q 扫码登录 docker run -v  \`pwd\`/config.json:/app/config.json -it --rm dedao login -q ，cookie 登录不如扫码登录方便。后续将关闭 cookie 登录的功能。

**Comment by gigihubb** [comment]
同问 我用login -q扫码登录的代码 但是如下：
Macintosh-3:~ law$ docker run -v `pwd`/config.json:/app/config.json -it --rm dedao login -q
open /app/config.json: is a directory
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x600294]

goroutine 1 [running]:
github.com/yann0917/dedao-dl/config.(*Dedao).New(...)
	/build/config/dedao.go:27
github.com/yann0917/dedao-dl/config.(*ConfigsData).ActiveUserService(...)
	/build/config/config.go:238
github.com/yann0917/dedao-dl/cmd/app.getService()
	/build/cmd/app/base.go:22 +0x34
github.com/yann0917/dedao-dl/cmd/app.LoginByQr()
	/build/cmd/app/login.go:27 +0x20
github.com/yann0917/dedao-dl/cmd.glob..func10(0xe13020?, {0x75caf3?, 0x1?, 0x1?})
	/build/cmd/login.go:25 +0xc0
github.com/spf13/cobra.(*Command).execute(0xe13020, {0x40001920f0, 0x1, 0x1})
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x5e0
github.com/spf13/cobra.(*Command).ExecuteC(0xe13300)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x368
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/yann0917/dedao-dl/cmd.Execute(...)
	/build/cmd/root.go:29
main.main()
	/build/main.go:17 +0x2c

**Comment by gigihubb** [comment]
![WX20230503-083542@2x](https://user-images.githubusercontent.com/72908947/235917703-93fa3f5c-6ba9-4953-9e4e-e05719f62da8.png)
在docker里run好像有点问题？求教，谢谢！
