### ISSUE TITLE
听书的mp3下载速度很慢，能否参考电子书下载的方式，进行mp3下载的提速？

### ISSUE THREAD

**Issue by xukai504087493** [yann0917/dedao-dl#149]
课程和听书的mp3下载速度很慢，能否参考对电子书下载提速的方式，进行课程和听书mp3下载的提速？🚀🚀🚀

**Comment by yann0917** [comment]
首先纠正一下：电子书是参考听书mp3 下载优化的 🥲 
听书 mp3 下载速度慢是因为 `.ts` 文件过多， mp3 是 `.ts`文件分段下载之后合成的，一本正常的听书时长 20~30 分钟，里面有几十个ts 文件，下载之后还要经过 `ffmpeg` 合成一个 mp3 文件，这才是慢的原因。
