### ISSUE TITLE
（可能不合规的）电子书下载错误

### ISSUE THREAD

**Issue by rainrdx** [yann0917/dedao-dl#150]
[古人的生活世界](https://www.dedao.cn/ebook/detail?id=JblNOdGPBpZdjEgmN4JLq7yaRvKV206VNa01roMz6xYX5QDG8l9bnOeAkey1g25L) 下载的时候提示

Error: XML syntax error on line 1923: invalid UTF-8

我在猜是不是书本身做的有问题。感谢作者不断花时间更新。

**Comment by yann0917** [comment]
确实是电子书的问题，这个字都不显示了， 百度搜到的是『殢酒贪欢,不觉日晚,红霞映水』
![image](https://user-images.githubusercontent.com/25262709/196437181-a5a0aed3-658e-4fa0-9adf-11dec0121227.png)

**Comment by rainrdx** [comment]
总是谢谢作者辛苦！
