### ISSUE TITLE
抓取电子书时，无法捕获一段内的多种字体属性

### ISSUE THREAD

**Issue by blakehan** [yann0917/dedao-dl#157]
图书地址： https://www.dedao.cn/ebook/reader?id=kQX7yD4MVoN52PDAnlRdzK6qvg8XEwbM1R3ZJjBb7rO4ypxGa9LeQm1kYng9YzK5

名著中一段话内经常有多种字体。比如这里用仿宋表示法语，今楷表示俄语。
<img width="791" alt="image" src="https://user-images.githubusercontent.com/2180869/205493326-45208950-1324-4c20-97b4-60ecba979e0e.png">
SVG代码如下：
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/2180869/205493448-91dd82df-3a48-44c7-8a2a-fd0a90000499.png">
抓取以后仿宋和今楷都变成了苹方。
<img width="750" alt="image" src="https://user-images.githubusercontent.com/2180869/205493533-57fb11c8-7616-490c-8bce-45dfcf1468c6.png">

**Comment by blakehan** [comment]
Temporary fix:

<img width="938" alt="image" src="https://user-images.githubusercontent.com/2180869/205495737-490b95ce-1d7f-4032-b485-e9b90d863804.png">

**Comment by yann0917** [comment]
bug #141 ,之前没遇到过这种情况，就没处理。

**Comment by yann0917** [comment]
你这种处理方式不具有普遍性，我再想想其他办法。

**Comment by yann0917** [comment]
> [comment.diff.txt](https://github.com/yann0917/dedao-dl/files/10148574/comment.diff.txt) @yann0917 感谢回复。我做了个简单粗暴的修改，现在可以支持这种注释格式了

9488_庄子（中华经典名著全本全注全译丛书）_方勇 译注 这本书脚注是`(1)` 这样的，但是不需要超链接，比如《逍遥游》这一段
![image](https://user-images.githubusercontent.com/25262709/205843719-a28d76e2-619e-456a-8dfa-67182ad6ec3c.png)

所以我统一修改一下：
根据  svg 的 top 属性来判断，解析文本的时候 **如果本次循环的 top 比上一次的小说明是上标**，标注一下解析出来的是**脚注**， 然后 在生成  html的时候用`<sup></sup>` 标签，但是超链接的脚注暂时还是没有办法。

**Comment by blakehan** [comment]
@yann0917 我改了下代码，现在应该可以适用于所有情况了

[comment.diff.txt](https://github.com/yann0917/dedao-dl/files/10164246/comment.diff.txt)

**Comment by yann0917** [comment]
![image](https://user-images.githubusercontent.com/25262709/205908105-030da1ea-0062-495c-81c3-af8fe1fa442e.png)
可以了
