### ISSUE TITLE
电子书下载不全

### ISSUE THREAD

**Issue by rainrdx** [yann0917/dedao-dl#160]
感谢作者费心。我这也是第一次遇到这样的问题。即一本书的章节还有剩余的内容，但是下载下来的版本里就没有了。

一个例子是：
https://d.dedao.cn/E4UcXsop8aYBVyDc

在最后一章，下载下来的版本到第五小节为止，但是实际上这一章还有差不多一般的内容。总是多谢作者。

**Comment by rainrdx** [comment]
意外又发现了一个缺得更多的书。感谢作者

https://d.dedao.cn/E54ksV5AevHdaQEf

**Comment by yann0917** [comment]
章节内容太多，内容请求不完整导致的，已解决。

**Comment by rainrdx** [comment]
总是感谢作者花时间修补。及祝新年快乐！
