### ISSUE TITLE
can't download ebook

### ISSUE THREAD

**Issue by clarence-glx** [yann0917/dedao-dl#164]
chapterID:"Chapter10.xhtml"
chapterID:"Chapter11.xhtml"
chapterID:"Chapter12.xhtml"
chapterID:"Chapter13.xhtml"
chapterID:"Chapter14.xhtml"
正在生成文件：【output/Ebook/*****.pdf】 panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/yann0917/dedao-dl/utils.parseFootNoteDelimiter(0xc0035ef950?)
	/Users/yabo/wwwroot/dedao-dl/utils/svg2html.go:728 +0x2bb
github.com/yann0917/dedao-dl/utils.GenLineContentByElement(0xc00088e740)
	/Users/yabo/wwwroot/dedao-dl/utils/svg2html.go:595 +0x4b
github.com/yann0917/dedao-dl/utils.OneByOneHtml({0xbcd2fb, 0x3}, 0x4, 0xc0000f80e0, {0xc00049ba30?, 0x1?, 0x1?})
	/Users/yabo/wwwroot/dedao-dl/utils/svg2html.go:311 +0x259
github.com/yann0917/dedao-dl/utils.Svg2Pdf({0xc000501060, 0x1f}, {0xc000672000, 0x12, 0xc0000fb400?})
	/Users/yabo/wwwroot/dedao-dl/utils/svg2html.go:121 +0x2c5
github.com/yann0917/dedao-dl/cmd/app.(*EBookDownload).Download(0xc00049bd50)
	/Users/yabo/wwwroot/dedao-dl/cmd/app/download.go:186 +0x325
github.com/yann0917/dedao-dl/cmd/app.Download(...)
	/Users/yabo/wwwroot/dedao-dl/cmd/app/download.go:207
github.com/yann0917/dedao-dl/cmd.glob..func8(0x12878e0?, {0xc000228fc0?, 0x1, 0x3?})
	/Users/yabo/wwwroot/dedao-dl/cmd/download.go:88 +0xd4
github.com/spf13/cobra.(*Command).execute(0x12878e0, {0xc000228f60, 0x3, 0x3})
	/Users/yabo/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x1285380)
	/Users/yabo/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/yabo/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/yann0917/dedao-dl/cmd.Execute(...)
	/Users/yabo/wwwroot/dedao-dl/cmd/root.go:29
main.main()
	/Users/yabo/wwwroot/dedao-dl/main.go:17 +0x25

fedora37 x86_64

**Comment by yann0917** [comment]
这个  bug和 #163 一样，能否告知书名，或者请拉取源码编译后再试一下，我这边修复过，但是没打最新 tag。
