### ISSUE TITLE
Can't download pdf books

### ISSUE THREAD

**Issue by csmasterpath** [yann0917/dedao-dl#167]
**Describe the bug**
pdfg create err: &errors.errorString{s:"Loading pages (1/6)\r\n[>                                                           ] 0%\r[===>                                                        ] 5%\r[======>                                                     ] 10%\r[============>                                               ] 20%\r[============>                                               ] 21%\r[==============>                                             ] 24%\r[===============>                                            ] 26%\r[===================>                                        ] 32%\r[===================>                                        ] 33%\r[=====================>                                      ] 35%\r[=====================>                                      ] 36%\r[=====================>                                      ] 36%\r[======================>                                     ] 38%\r[=======================>                                    ] 39%\r[========================>                                   ] 40%\r[========================>                                   ] 41%\rError: Failed to load http://file//D:\\360Downloads\\output\\Ebook\\cover.html, with network status code 3 and http status code 0 - Host file not found\r\nError: Failed loading page http://file//D:\\360Downloads\\output\\Ebook\\cover.html (sometimes it will work just to ignore this error with --load-error-handling ignore)\r\n[========================>                                   ] 41%\r[=========================>                                  ] 42%\r[=========================>                                  ] 42%\r[=========================>                                  ] 43%\r[==========================>                                 ] 44%\r[==========================>                                 ] 44%\r[===========================>                                ] 45%\r[===========================>                                ] 45%\r[===========================>                                ] 46%\r[===========================>                                ] 46%\r[============================>                               ] 47%\r[=============================>                              ] 49%\r[=============================>                              ] 49%\r[=================================>                          ] 55%\rExit with code 1 due to network error: HostNotFoundError\r\n"}
Error: Loading pages (1/6)
Error: Failed to load http://file//D:\360Downloads\output\Ebook\cover.html, with network status code 3 and http status code 0 - Host file not found
Error: Failed loading page http://file//D:\360Downloads\output\Ebook\cover.html (sometimes it will work just to ignore this error with --load-error-handling ignore)
Exit with code 1 due to network error: HostNotFoundError     ] 55%
**Failed to load http://file//D:\360Downloads\output\Ebook\cover.html**，  The reasons of the above problem might be that the cover's loadpath is fault, the loadpath might be missed the ':'  before the file word

**Comment by yann0917** [comment]
> **Describe the bug** pdfg create err: &errors.errorString{s:"Loading pages (1/6)\r\n[> ] 0%\r[===> ] 5%\r[======> ] 10%\r[============> ] 20%\r[============> ] 21%\r[==============> ] 24%\r[===============> ] 26%\r[===================> ] 32%\r[===================> ] 33%\r[=====================> ] 35%\r[=====================> ] 36%\r[=====================> ] 36%\r[======================> ] 38%\r[=======================> ] 39%\r[========================> ] 40%\r[========================> ] 41%\rError: Failed to load [http://file//D:\\360Downloads\\output\\Ebook\\cover.html](http://file//D:%5C%5C360Downloads%5C%5Coutput%5C%5CEbook%5C%5Ccover.html), with network status code 3 and http status code 0 - Host file not found\r\nError: Failed loading page [http://file//D:\\360Downloads\\output\\Ebook\\cover.html](http://file//D:%5C%5C360Downloads%5C%5Coutput%5C%5CEbook%5C%5Ccover.html) (sometimes it will work just to ignore this error with --load-error-handling ignore)\r\n[========================> ] 41%\r[=========================> ] 42%\r[=========================> ] 42%\r[=========================> ] 43%\r[==========================> ] 44%\r[==========================> ] 44%\r[===========================> ] 45%\r[===========================> ] 45%\r[===========================> ] 46%\r[===========================> ] 46%\r[============================> ] 47%\r[=============================> ] 49%\r[=============================> ] 49%\r[=================================> ] 55%\rExit with code 1 due to network error: HostNotFoundError\r\n"} Error: Loading pages (1/6) Error: Failed to load [http://file//D:\360Downloads\output\Ebook\cover.html](http://file//D:%5C360Downloads%5Coutput%5CEbook%5Ccover.html), with network status code 3 and http status code 0 - Host file not found Error: Failed loading page [http://file//D:\360Downloads\output\Ebook\cover.html](http://file//D:%5C360Downloads%5Coutput%5CEbook%5Ccover.html) (sometimes it will work just to ignore this error with --load-error-handling ignore) Exit with code 1 due to network error: HostNotFoundError ] 55% **Failed to load [http://file//D:\360Downloads\output\Ebook\cover.html**，](http://file//D:%5C360Downloads%5Coutput%5CEbook%5Ccover.html**%EF%BC%8C) The reasons of the above problem might be that the cover's loadpath is fault, the loadpath might be missed the ':' before the file word

1. 麻烦告知一下书名
2. 看错误 log `Error: Failed to load [http://file//D:\\360Downloads\\output\\Ebook\\cover.html](http://file//D:%5C%5C360Downloads%5C%5Coutput%5C%5CEbook%5C%5Ccover.html)` 文件路径很奇怪，应该是wkhtmltopdf 没用对参考[wkhtmltopdf issue](https://github.com/wkhtmltopdf/wkhtmltopdf/issues/4033)

**Comment by csmasterpath** [comment]
吴军文明之光

**Comment by csmasterpath** [comment]
感谢回复，日志中给出的路径“[http://file//D:\360Downloads\output\Ebook\cover.html**，](http://file//D:%5C360Downloads%5Coutput%5CEbook%5Ccover.html**%EF%BC%8C)”，看起来是在file后面缺少了冒号

**Comment by yann0917** [comment]
> 感谢回复，日志中给出的路 `[http://file//D:\360Downloads\output\Ebook\cover.html]` ，看起来是在file后面缺少了冒号

我这边是 MacOS ,下载这本书没报错，而且封面文件是保存在本地的，路径不可能有 `http://`开头，这点很奇怪。

请确认一下：下载其他电子书的 pdf 版本也报错吗？如果是的话，应该是不兼容 Windows 的原因，我可以改一下=。

**Comment by csmasterpath** [comment]
未修改之前下载所有的pdf都是同样的错误
修改之后，错误如下
Error: Failed to load , with network status code 301 and http status code 0 - Protocol "" is unknown
Error: Failed loading page file:\D:\360Downloads\dedao-dl\Releases\output\Ebook\cover.html (sometimes it will work just to ignore this error with --load-error-handling ignore)
Exit with code 1 due to network error: ProtocolUnknownError  ] 55%
协议未知错误，是不兼容win吗

**Comment by csmasterpath** [comment]
但是对于html格式，不也是先下载了不同的html然后合成一个文件的吗，这个为什么在html那没问题，在pdf这会在加载封面时候报错呢，好奇怪

**Comment by csmasterpath** [comment]
(dedao-dl/utils/svg2html.go)[https://github.com/yann0917/dedao-dl/blob/main/utils/svg2html.go#L213]将file去掉之后，正确生成pdf，但是不知道这样改是否会引起其他系统的错误

**Comment by csmasterpath** [comment]
> > 感谢回复，日志中给出的路 `[http://file//D:\360Downloads\output\Ebook\cover.html]` ，看起来是在file后面缺少了冒号
> 
> 如果是文件路径兼容性问题把这一行 `//` 改为 `\\` 试试
> 
> https://github.com/yann0917/dedao-dl/blob/2f55454aa15578753bbd6f5a30bb1847f35d6bdc/utils/svg2html.go#L213

将file去掉之后，正确生成pdf，但是不知道这样改是否会引起其他系统的错误

**Comment by yann0917** [comment]
> 但是对于html格式，不也是先下载了不同的html然后合成一个文件的吗，这个为什么在html那没问题，在pdf这会在加载封面时候报错呢，好奇怪

不是的，html 格式，下载没保存到本地，直接解析 svg 转化成 html 的；PDF 格式的首先要根据封面图片生成本地 html ，然后设置封面的时候获取本地路径「错误出现的位置」，合成完之后删除封面 html。

**Comment by yann0917** [comment]
> > > 感谢回复，日志中给出的路 `[http://file//D:\360Downloads\output\Ebook\cover.html]` ，看起来是在file后面缺少了冒号
> > 
> > 
> > 如果是文件路径兼容性问题把这一行 `//` 改为 `\\` 试试
> > https://github.com/yann0917/dedao-dl/blob/2f55454aa15578753bbd6f5a30bb1847f35d6bdc/utils/svg2html.go#L213
> 
> 将file去掉之后，正确生成pdf，但是不知道这样改是否会引起其他系统的错误

那倒不会，这个只是加载PDF封面用的。 我判断一下系统，如果是 Windows 不加 `file://`
