### ISSUE TITLE
下载张宏杰的《曾国藩传》pdf格式电子书，出现乱码

### ISSUE THREAD

**Issue by lookTT** [yann0917/dedao-dl#168]
使用操作系统： Debian11

描述：
下载张宏杰的《曾国藩传》pdf格式电子书，出现乱码

执行语句：
$ ./dedao-linux-amd64 dle 4037 -t 1

电子书截图
![image](https://user-images.githubusercontent.com/6091731/234744642-9e0d56d0-0b4f-4d3c-9bff-3d6691f80df0.png)

其他说明
这本书的html，epub格式都正常显示，只有pdf是乱码

**Comment by yann0917** [comment]
是不是操作系统缺少中文字体导致的？

**Comment by lookTT** [comment]
> 是不是操作系统缺少中文字体导向的？

我来试试

**Comment by lookTT** [comment]
> 是不是操作系统缺少中文字体导致的？

装了中文字库完美解决
`sudo apt-get install fonts-wqy-microhei`
重启下系统就好了
