### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by gigihubb** [yann0917/dedao-dl#169]
![WX20230503-094454@2x](https://user-images.githubusercontent.com/72908947/235934348-6995fc4e-0d9d-463a-8551-e41e7e55923c.png)

求教，谢谢！

**Comment by gigihubb** [comment]
![WX20230503-094821@2x](https://user-images.githubusercontent.com/72908947/235935491-e175e0af-3d83-4495-a394-9a97e1c64c75.png)

试着用cookie登陆也不行。。求助，谢谢！

**Comment by gigihubb** [comment]
![WX20230503-103113@2x](https://user-images.githubusercontent.com/72908947/235947592-48255e2e-ec23-46f1-8f6a-b5e3c1677263.png)

用cookie登陆也不行。。求助，谢谢！

**Comment by yann0917** [comment]
`config.json` 是配置文件，不是目录。是不是你执行命令所在目录下存在一个 `config.json`目录导致的？

**Comment by gigihubb** [comment]
谢谢！
是的，我执行命令所在目录下存在一个 config.json目录，我把它删了。现在可以登陆了。
