### ISSUE TITLE
获取ebook列表时出错了

### ISSUE THREAD

**Issue by liamli** [yann0917/dedao-dl#170]
<img width="569" alt="image" src="https://user-images.githubusercontent.com/732607/236108118-b2ba5ba2-855f-49ff-a9e7-b409737377cc.png">

**Comment by yann0917** [comment]
我这边无法复现，有没有一种可能，你的书架上没有电子书。

**Comment by yann0917** [comment]
更新代码：已购列表为空的，直接抛出错误。
