### ISSUE TITLE
关于'config.json'，但是实际项目中并无该文件。

### ISSUE THREAD

**Issue by baiwei0703** [yann0917/dedao-dl#172]
README.md 中提到的docker运行方法下，有关于'config.json'，但是实际项目中并无该文件。这个文件是会自动生成的吗？直接运行docker run 的时候，会提示‘ /app/config.json配置文件不能是目录’。

**Comment by yann0917** [comment]
> README.md 中提到的docker运行方法下，有关于'config.json'，但是实际项目中并无该文件。这个文件是会自动生成的吗？直接运行docker run 的时候，会提示‘ /app/config.json配置文件不能是目录’。

1. 这个文件是会自动生成的
2. 提示‘ /app/config.json配置文件不能是目录’ ，请删除目录。

**Comment by yann0917** [comment]
参考 #169
