### ISSUE TITLE
序号列表的第一行解析错位

### ISSUE THREAD

**Issue by OrNatosY** [yann0917/dedao-dl#174]
导出 PDF 以及 eBook 格式时，如果遇到了序号列表，则字符 `1.` 会被解析到序号列表的上一行，例如：

```
正确的解析格式：

1. 哈哈哈
2. 哈哈哈
3. 哈哈哈
```

```
实际上的解析格式：1
.哈哈哈
2. 哈哈哈
3. 哈哈哈
```
![3761689565496_ pic](https://github.com/yann0917/dedao-dl/assets/43162204/da8b4138-dbfe-4275-8029-fc07fbcafbe4)

**Comment by yann0917** [comment]
估计是识别成下标了，我记录一下：例子：小强升职记，第三章第一节《臣服与拖延》
