### ISSUE TITLE
Error: XML syntax error on line 10376: invalid UTF-8

### ISSUE THREAD

**Issue by iamhongliang** [yann0917/dedao-dl#176]
**Describe the bug**
some books raise Error: XML syntax error on line 10376: invalid UTF-8 while downloading:

eg: 

book id: 58874
bookname： 苏东坡新传（李一冰）

Really appreciate to author's great efforts.

**Comment by yann0917** [comment]
电子书的问题，可以反馈给官方 #150

**Comment by yann0917** [comment]
出错的位置如下：

![image](https://github.com/yann0917/dedao-dl/assets/25262709/fa5ef7bd-1510-4769-aec9-c0c24bb22659)
