### ISSUE TITLE
无法加载登入二维码

### ISSUE THREAD

**Issue by YQHan** [yann0917/dedao-dl#180]
<img width="396" alt="Screenshot 2023-08-20 at 11 39 06" src="https://github.com/yann0917/dedao-dl/assets/9411155/2c90f88a-a636-4af1-8728-9354c07cc38f">
无法加载登入二维码。。。

**Comment by jxzzlfh** [comment]
得到网页版最近好像加入了不定时安全验证，导致加载失败
