### ISSUE TITLE
Invalid UTF8

### ISSUE THREAD

**Issue by rainrdx** [yann0917/dedao-dl#182]
**Describe the bug**

Error: XML syntax error on line 728: invalid UTF-8

**To Reproduce**
[电子书地址](https://www.dedao.cn/ebook/detail?id=lxaVvndNG6D4kgLJ2OKxqVMmE1zXPwVpZnWAdjyQeYR75vbaBnr9ol8pZERLg1my)

总是感谢作者花这么多时间维护。谢谢！

**Comment by yann0917** [comment]
电子书的问题，我处理一下吧，如果解析不了，也输出`𨚗`

![image](https://github.com/yann0917/dedao-dl/assets/25262709/bd8a6e94-687c-423b-8652-06b752e62efa)

**Comment by rainrdx** [comment]
真的是总是多谢作者花时间十分感谢！

**Comment by yann0917** [comment]
试了一下不行，编码不对，直接解析不出来，如果跳过错误的话，整章内容都没了，直接反馈电子书官方等待改正吧。

**Comment by rainrdx** [comment]
对的我也觉得反馈给官方最简单了。谢谢。

**Comment by yann0917** [comment]
官方已经修复好了

**Comment by rainrdx** [comment]
我去这也太快了谢谢作者告知

**Comment by jmp0xf** [comment]
> 电子书的问题，我处理一下吧，如果解析不了，也输出`𨚗`
> 
> ![image](https://user-images.githubusercontent.com/25262709/265269822-bd8a6e94-687c-423b-8652-06b752e62efa.png)

请问怎样根据报错快速定位到问题段落呢

**Comment by yann0917** [comment]
> 请问怎样根据报错快速定位到问题段落呢

打开注释，会保存每个章节的原始内容，如果要显示哪个章节出问题的话，可以在 `utils/svg2html.go` 345行下面打印想要的内容。

https://github.com/yann0917/dedao-dl/blob/6ee2ce6954148c0c5868ce04dddd3d03577b22a6/cmd/app/ebook.go#L96

**Comment by yann0917** [comment]
> 试了一下不行，编码不对，直接解析不出来，如果跳过错误的话，整章内容都没了，直接反馈电子书官方等待改正吧。

想到了一个办法，在解析svg 之前，先过滤一下非UTF-8编码的字符，这样就不会报无效的UTF-8编码错误，并且整章内容都在，只是部分字符因编码问题显示乱码而已。
