### ISSUE TITLE
Error: XML syntax error on line 9784: invalid UTF-8，导致无法生成epub格式的文件

### ISSUE THREAD

**Issue by xukai504087493** [yann0917/dedao-dl#183]
下载这种技术类书籍时，会报以下错误，同时导致无法生成epub格式的文件：
Error: XML syntax error on line 9784: invalid UTF-8

书名：《Vue.js设计与实现》，这本报错书网址：
https://www.dedao.cn/ebook/detail?id=donM9vjLM8m6d5YQ7lvJGVz2Xgaqb3pdaG3nBRyejENkP1KZo9rD4OApxpxkY7Ke

**Comment by yann0917** [comment]
电子书问题，参考 #182
