### ISSUE TITLE
下载电子书出错“Error: XML syntax error on line 25492: invalid UTF-8”

### ISSUE THREAD

**Issue by chenbin2005** [yann0917/dedao-dl#194]
**Describe the bug**
1.2.0版本dedao-windows-amd64.exe，尝试下载电子书“中华二千年史（全九册）”，结果出错

**To Reproduce**
步骤如下：
1）dedao-windows-amd64 login -q     扫码正常登录
2）dedao-windows-amd64 ebook        列出已购买的电子书也正常
3）dedao-windows-amd64 dle 28048 -t 1      输出如下
chapterID:"PART1_chapter-7.xhtml"
chapterID:"Section0001.xhtml"
chapterID:"cover.xhtml"
chapterID:"copyright.xhtml"
chapterID:"PART1_chapter-3.xhtml"
chapterID:"PART1_chapter-1.xhtml"
chapterID:"PART1_chapter-2.xhtml"
chapterID:"PART1_chapter-5.xhtml"
chapterID:"PART1_chapter-4.xhtml"
chapterID:"PART1_chapter-6.xhtml"
chapterID:"PART1_chapter-8.xhtml"
chapterID:"PART1_chapter-9.xhtml"
chapterID:"PART1_chapter-10.xhtml"
chapterID:"PART1_chapter-11.xhtml"
chapterID:"Section0002.xhtml"
chapterID:"PART2_chapter-1.xhtml"
chapterID:"PART2_chapter-2.xhtml"
chapterID:"PART2_chapter-3.xhtml"
chapterID:"PART2_chapter-4.xhtml"
chapterID:"PART2_chapter-5.xhtml"
chapterID:"PART2_chapter-6.xhtml"
chapterID:"Section0003.xhtml"
chapterID:"PART3_chapter-1.xhtml"
chapterID:"PART3_chapter-2.xhtml"
chapterID:"PART3_chapter-3.xhtml"
chapterID:"PART3_chapter-4.xhtml"
chapterID:"PART3_chapter-5.xhtml"
chapterID:"PART3_chapter-6.xhtml"
chapterID:"Section0004.xhtml"
chapterID:"PART4_chapter-1.xhtml"
chapterID:"PART4_chapter-2.xhtml"
chapterID:"PART4_chapter-3.xhtml"
chapterID:"PART4_chapter-4.xhtml"
chapterID:"PART4_chapter-5.xhtml"
chapterID:"PART4_chapter-6.xhtml"
chapterID:"PART4_chapter-7.xhtml"
chapterID:"PART4_chapter-8.xhtml"
chapterID:"Section0005.xhtml"
chapterID:"PART5_chapter-1.xhtml"
chapterID:"PART5_chapter-2.xhtml"
chapterID:"PART5_chapter-3.xhtml"
chapterID:"PART5_chapter-4.xhtml"
chapterID:"PART5_chapter-5.xhtml"
chapterID:"PART5_chapter-6.xhtml"
chapterID:"PART5_chapter-7.xhtml"
chapterID:"PART5_chapter-8.xhtml"
chapterID:"PART5_chapter-9.xhtml"
chapterID:"PART5_chapter-10.xhtml"
chapterID:"PART5_chapter-11.xhtml"
chapterID:"PART5_chapter-12.xhtml"
chapterID:"PART5_chapter-13.xhtml"
chapterID:"Section0006.xhtml"
chapterID:"PART6_chapter-1.xhtml"
chapterID:"PART6_chapter-2.xhtml"
chapterID:"PART6_chapter-3.xhtml"
chapterID:"PART6_chapter-4.xhtml"
chapterID:"PART6_chapter-5.xhtml"
chapterID:"PART6_chapter-6.xhtml"
chapterID:"PART6_chapter-7.xhtml"
chapterID:"PART6_chapter-8.xhtml"
chapterID:"PART6_chapter-9.xhtml"
chapterID:"PART6_chapter-10.xhtml"
chapterID:"Section0007.xhtml"
chapterID:"PART7_chapter-1.xhtml"
chapterID:"PART7_chapter-2.xhtml"
chapterID:"PART7_chapter-3.xhtml"
chapterID:"PART7_chapter-4.xhtml"
chapterID:"PART7_chapter-5.xhtml"
chapterID:"PART7_chapter-6.xhtml"
chapterID:"PART7_chapter-7.xhtml"
chapterID:"Section0008.xhtml"
chapterID:"PART8_chapter-1.xhtml"
chapterID:"PART8_chapter-2.xhtml"
chapterID:"PART8_chapter-3.xhtml"
chapterID:"PART8_chapter-4.xhtml"
chapterID:"PART8_chapter-5.xhtml"
chapterID:"PART8_chapter-6.xhtml"
chapterID:"Section0009.xhtml"
chapterID:"PART9_chapter-1.xhtml"
chapterID:"PART9_chapter-2.xhtml"
chapterID:"PART9_chapter-3.xhtml"
chapterID:"PART9_chapter-4.xhtml"
chapterID:"PART9_chapter-5.xhtml"
chapterID:"PART9_chapter-6.xhtml"
chapterID:"PART9_chapter-7.xhtml"
Error: XML syntax error on line 25492: invalid UTF-8
Usage:
  dedao-dl dle [flags]

Examples:
dedao-dl dle 123 -t 1

Flags:
  -t, --downloadType int   下载格式, 1:html, 2:PDF文档, 3:epub (default 1)
  -h, --help               help for dle

这本书“中华二千年史（全九册）”相对是比较长的。但是从程序的输出中实在看不出是哪里出错了？

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10 22H2 19045.3570
 - Browser : chrome 118.0.5993.71（正式版本） （64 位）
 - Version dedao-dl 是 1.2.0

**Smartphone (please complete the following information):**

**Additional context**
 如果可能的话，希望添加一个开关，可以输出程序运行的log，也方便后续定位问题。
另外，下载电子书过程中出错，可否把前面没出错的先下载下来？现在这种出错了output目录里面啥都没有的情况，让人比较有挫败感 谢谢！

**Comment by yann0917** [comment]
- 出现[invalid UTF-8 是因为电子书内容有误，可以反馈给电子书官方。

- 如果出错了，只下载一半应该是可以的，但是我不能这样做，这样的话内容不完整又会有人提issue的

- 关于错误信息定位的提议很好，我看下能不能把错误信息展示出来。

**Comment by chenbin2005** [comment]
内容有误大概是指啥情况？因为这本书在得到App和得到PC网站(https://www.dedao.cn/ebook/reader?id=XXXXXXX)上面都是正常阅读的。我特意看了看最后几个章节，但无法看出html页面上有啥问题。所以说，如果有log可以定位是那一段解析出错的话，找问题会好很多
