### ISSUE TITLE
请问课程内容能做合并么 分开看不方便

### ISSUE THREAD

**Issue by longbai** [yann0917/dedao-dl#198]

**Comment by yann0917** [comment]
目前没有这个功能，不过你可以使用其他工具做合并，参考：

1. [三步实现多个markdown合并输出一个 pdf](https://blog.csdn.net/qq_42532128/article/details/119411991)
2. [markdown一步生成电子书: 支持PDF、Mobi、EPUB格式](https://github.com/phodal/ebook-boilerplate)
