### ISSUE TITLE
exec: "ffmpeg": executable file not found in $PATH

### ISSUE THREAD

**Issue by kerncoola** [yann0917/dedao-dl#2]
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/123/Library/Caches/go-build"
GOENV="/Users/123/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/123/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/123/go"
GOPRIVATE=""
GOPROXY="https://goproxy.cn"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/g9/hclfswm94yg5g7njg7lnk9200000gn/T/go-build637456610=/tmp/go-build -gno-record-gcc-switches -fno-common"

**Comment by kerncoola** [comment]
大佬看下Mac环境下ffmpeg是直接放到$PATH即GOPATH="/Users/123/go"目录下吗

**Comment by yann0917** [comment]
> 大佬看下Mac环境下ffmpeg是直接放到$PATH即GOPATH="/Users/123/go"目录下吗

直接 brew 安装就行，brew 已经帮你维护好了 `brew install ffmpeg`

**Comment by kerncoola** [comment]
好的，谢谢
