### ISSUE TITLE
使用 dedao-dl dlo 时提示“指定要下载的类型不存在”【breaking：官方接口变更】

### ISSUE THREAD

**Issue by Lavan1874** [yann0917/dedao-dl#201]
使用 dedao-dl dlo **** -t 1 下载 mp3 时提示“指定要下载的类型不存在”

dedao-dl dlo 6535 -t 1
Error: 指定要下载的类型不存在：YV45oGQADnpXWJKoEr1M6kwe9OL8vN
Usage:
  dedao-dl dlo [flags]

Examples:
dedao-dl dlo 123 -t 1

Flags:
  -t, --downloadType int   下载格式, 1:mp3, 2:PDF文档, 3:markdown文档 (default 1)
  -h, --help               help for dlo

<img width="675" alt="截屏2024-01-21 22 39 51" src="https://github.com/yann0917/dedao-dl/assets/47176003/4f68be60-a97c-415e-94b9-97c06d0e7d90">

dedao-dl dlo **** -t 2下载 PDF 正常

**Comment by Lavan1874** [comment]
使用 gui 下载时同样提示指定”要下载的类型不存在“
<img width="1392" alt="截屏2024-01-21 22 53 01" src="https://github.com/yann0917/dedao-dl/assets/47176003/babd5540-5d72-4e60-824e-e6f30853e9ad">

**Comment by yann0917** [comment]
得到 web 端接口变更，导致拿不到 m3u8 url

**Comment by Lavan1874** [comment]
感谢回复
是否可能与近期官方上线了浏览器听书功能有关？存在修复的可能吗？

**Comment by yann0917** [comment]
> 感谢回复 是否可能与近期官方上线了浏览器听书功能有关？存在修复的可能吗？

是的，没上线浏览器听书功能之前，我是通过其他接口拿到数据的。上线之后逻辑变了，理论上是能拿到数据的，我先研究一下接口。
