### ISSUE TITLE
not able to download MP3 anymore... used to work okay. Please help

### ISSUE THREAD

**Issue by Ethanww3** [yann0917/dedao-dl#202]
not able to download MP3 anymore... used to work okay. Please help

Here is the screen shot:

https://imgur.com/a/v1fJnPN

Update dedao-dl in GO, update ffmpeg, still not working.  It used to work fine like 2 weeks ago.

**Comment by Ethanww3** [comment]
NVM, its working again after the new update which launched 1 hour ago....   big thanks again.

**Comment by Ethanww3** [comment]
大佬, 还有一个问题, 我的桌面版本没有QR code 去scan, 你在教程里说 

本应用上登录后再登录官方网页版会导致保存的 cookie 失效，使用 rm -rf ~/.config/dedao/config.json 删除配置信息后重新登陆本应用即可。 

我在node, npm, go 里输入这个指令都说找不到文件,  自己搜了C盘也没有找到这个 .config/dedao/config.json 

请问如何解决，  感激不尽！

**Comment by yann0917** [comment]
听书音频下失败问题，更新到v1.2.4 参考 #201
