### ISSUE TITLE
ebook pdf格式输出错误

### ISSUE THREAD

**Issue by likai2223** [yann0917/dedao-dl#204]
.\dedao-windows-amd64.exe dle XXX -t 2
下载ebook，生成pdf格式，都有此错误

正在生成文件：【output\Ebook\XXX.pdf】 
pdfg create err: &errors.errorString{s:"exec: no command"}
Error: exec: no command

**Comment by yann0917** [comment]
本地没安装 [wkhtmltopdf](https://wkhtmltopdf.org/downloads.html)
