### ISSUE TITLE
请教大佬问题

### ISSUE THREAD

**Issue by bu-code** [yann0917/dedao-dl#205]
首先感谢大佬开发，十分感谢！
其次想问下是不是下不到每本书的阅读样式css，下载的epub和网页或app端相比，阅读时发现文字样式不同，不够精美，当然能看问题就不大。

**Comment by yann0917** [comment]
网页端是 svg 渲染的，每次改动(窗口大小，分栏，字体)，都会请求服务端重新返回 svg。而下载整本书，没办法这样搞，按预先设置好的参数，解析 svg 为文本，再根据 svg 里的参数解析样式的。
