### ISSUE TITLE
Mac m1 版本是不是不支持？

### ISSUE THREAD

**Issue by jessy4002** [yann0917/dedao-dl#216]

**Comment by jessy4002** [comment]
我试了大半天到安装的dedao这一步一直没有反应。后来一看darwin是amd的格式，而m1的Mac是arm的，所以是不能用吗？

**Comment by yann0917** [comment]
我编译好的没有m1版本的，你用源码编译一下看看，应该是支持的。

**Comment by jessy4002** [comment]
感谢大佬的回复。我这是个编码小白，费了好大劲才一步步往下学着做。能不能给个步骤怎么做源码编译？如果有直接arm版本那就太感谢了🥹
