### ISSUE TITLE
按照步骤走到运行docker这里卡住了，运行第一段build命令没反应，是不是docker的path什么问题？还是单纯因为arm不支持的问题？

### ISSUE THREAD

**Issue by jessy4002** [yann0917/dedao-dl#217]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yann0917** [comment]
1. docker 里运行的并不是arm 架构的程序。
2. 没有具体的问题描述我很难解决你的问题。
3. docker 门槛高的话，可以不用，本地源码build即可，源码跟电脑是什么架构无关。
