### ISSUE TITLE
docker-build 报错

### ISSUE THREAD

**Issue by ioswater** [yann0917/dedao-dl#218]
failed to solve: process "/bin/sh -c echo @3.16 https://mirrors.aliyun.com/alpine/v3.16/community > /etc/apk/repositories     && echo @3.16 https://mirrors.aliyun.com/alpine/v3.16/main >> /etc/apk/repositories     && echo @edge https://mirrors.aliyun.com/alpine/edge/testing >> /etc/apk/repositories     && apk update     && apk add --no-cache ffmpeg@3.16 tzdata@3.16 chromium@3.16     && apk add --no-cache --allow-untrusted harfbuzz@3.16 nss@3.16 freetype@3.16     ttf-freefont@3.16 wqy-zenhei@edge     && cp -r -f /usr/share/zoneinfo/Asia/Shanghai /etc/localtime     && rm -rf /var/cache/apk/*" did not complete successfully: exit code: 1

docker运行指令包错，没有详细信息，这种怎么解决呀？

**Comment by yann0917** [comment]
重启docker试试

**Comment by ioswater** [comment]
还有其他方法么？重启试了，不行。

**Comment by ioswater** [comment]
因为没有详细的报错，就只有上面的那个提示。我这边几台电脑都是一样的报错。是因为m1芯片吗？

**Comment by yann0917** [comment]
> 因为没有详细的报错，就只有上面的那个提示。我这边几台电脑都是一样的报错。是因为m1芯片吗？

M1 芯片的我没测试过，回头找一台试一下。

**Comment by ioswater** [comment]
好的，麻烦有消息了回一下解决方案。给作者点赞！！！

**Comment by yann0917** [comment]
找到问题了，是中文字体修改了镜像地址，导致出错的，已更新 dockerfile，并且确认可以 build 成功。
