### ISSUE TITLE
同时保留课程合并前后的markdown

### ISSUE THREAD

**Issue by gengjiawen** [yann0917/dedao-dl#220]
**Is your feature request related to a problem? Please describe.**

同时保留课程合并前后的markdown

**Describe the solution you'd like**

dedao-dl dl 123 -t 3 -m 保留独立的md

**Describe alternatives you've considered**

**Additional context**

**Comment by yann0917** [comment]
去掉-m 参数就行，这其实不是合并，而是把所有内容写在同一个文件里，而不是生成多个文件然后再合并文件。

**Comment by gengjiawen** [comment]
或者输出个目录文件保存下文件的先后顺序，自己merge也行

**Comment by yann0917** [comment]
> 或者输出个目录文件保存下文件的先后顺序，自己merge也行

执行两遍就行：
把 -m 去掉，保存的就是单个文件
把 -m 加上，只保留合并后的文件

**Comment by gengjiawen** [comment]
> > 或者输出个目录文件保存下文件的先后顺序，自己merge也行
> 
> 执行两遍就行： 把 -m 去掉，保存的就是单个文件 把 -m 加上，只保留合并后的文件

但这个会下载两遍，速度很慢

**Comment by yann0917** [comment]
> > > 或者输出个目录文件保存下文件的先后顺序，自己merge也行
> > 
> > 
> > 执行两遍就行： 把 -m 去掉，保存的就是单个文件 把 -m 加上，只保留合并后的文件
> 
> 但这个会下载两遍，速度很慢

如果课程多的话，确实有这个问题，我处理一下。

**Comment by yann0917** [comment]
处理好了，有空看下，最近太忙了，一直没空。
