### ISSUE TITLE
断点下载

### ISSUE THREAD

**Issue by gengjiawen** [yann0917/dedao-dl#221]
**Is your feature request related to a problem? Please describe.**
失败了，目前看日志是又重新下载了（因为比较慢）
正在生成文件：【《单身女性的时代》1：不能结婚还是不肯结婚？】 完成
unexpected EOF
Error: unexpected EOF
Usage:
  dedao-dl dl [flags]
Examples:
dedao-dl dl 123 -t 1 -m

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yann0917** [comment]
不支持，断点下载是需要服务端支持的，官方接口并没有直接提供下载链接。这个工具是根据官方的接口合成音频，文字，保存到本地。并不能知道是哪里出错了，也不知道下载了多少，合成了多少，所以简单粗暴的方法是重新调接口合成一次。
