### ISSUE TITLE
下载课程中特定文章时报错

### ISSUE THREAD

**Issue by kueilin** [yann0917/dedao-dl#229]
**Describe the bug**
下载课程中特定文章时报错，谢谢您。

**To Reproduce**
docker run -v `pwd`/output:/app/output -v `pwd`/config.json:/app/config.json -it --rm dedao dl 93 3202 -t 3

**Expected behavior**
Error: []services.Content: services.Content.Duration: readUint64: unexpected character: �, error found in #10 byte of ...|uration":"490","size|..., bigger context ...|273","aliasId":"xxx","duration":"490","size":0,"sizeStr":"4.68MB"},{"contents":[{"t|...

**Comment by yann0917** [comment]
93 3202  是什么课程哪节课？

**Comment by kueilin** [comment]
> 93 3202 是什么课程哪节课？
93 万维钢精英日课第一季
3202 主场有多重要  

同一门课还有其他文章有类似问题。

**Comment by yann0917** [comment]
我没有这门课，没法复现出来，可能是课程是好几年前的，字段跟现在的不太兼容导致的。

**Comment by Joshzxj** [comment]
➜  ~ dedao-dl dl 87 -t 3
Error: []services.Content: services.Content.Duration: readUint64: unexpected character: �, error found in #10 byte of ...|uration":"2005","siz|..., bigger context ...|668","aliasId":"FpAZXMtuXbH0q7gv6iqq","duration":"2005","size":0,"sizeStr":"22.95MB"},{"type":"heade|...
Usage:
  dedao-dl dl [flags]
  
  
  ➜  ~ dedao-dl dl 86 -t 3
正在生成文件：【代罗振宇：致女儿书】 完成
正在生成文件：【《你不重要，你的喜欢很重要》纸质书上线】 完成
正在生成文件：【开始写作吧】 完成
正在生成文件：【写作课教案】 完成
正在生成文件：【从网络小说学习写作】 完成
正在生成文件：【忘掉文笔这件事】 完成
正在生成文件：【点评一篇文章】 完成
正在生成文件：【话术：撒谎和误导】 完成
正在生成文件：【捍卫你的审美】 完成
正在生成文件：【梵高和梵高奶奶】 完成
正在生成文件：【当代艺术和垃圾】 完成
正在生成文件：【有生之年应该去一次卢浮宫】 完成
正在生成文件：【第 50000 本】 完成
正在生成文件：【写作这件小事（番外篇）】 完成
正在生成文件：【在世界读书日提几个问题】 完成
正在生成文件：【基本书】 完成
正在生成文件：【本来不读书】 完成
正在生成文件：【你家客厅正中是什么】 完成
正在生成文件：【请你读一次《江城》】 完成
Error: []services.Content: services.Content.Duration: readUint64: unexpected character: �, error found in #10 byte of ...|uration":"558","size|..., bigger context ...|556","aliasId":"zLPR0jtzHgnGmLbahQHn","duration":"558","size":0,"sizeStr":"6.39MB"},{"contents":[{"t|...
Usage:
  dedao-dl dl [flags]


我还有一些其他的课挂了
能尝试加个try-except 或类似的错误捕获机制。这样当程序遇到格式错误或者无法解析的数据时，会跳过当前课程，继续下载下一个课程。
