### ISSUE TITLE
epub文件注释，calibre不兼容，无法隐藏

### ISSUE THREAD

**Issue by voidpainter** [yann0917/dedao-dl#232]
![2024-09-21_09-32](https://github.com/user-attachments/assets/957e851c-3ce5-4538-8461-09533a01f4a5)

这是下载的epub文件，calibre打开。
“三分钱...”的那段是注释，在 `<aside>` 标签里，这类标签原本应该在文档末尾的，点圆圈”注“会弹框。
除了一个个编辑 `xhtml` 还有别的办法吗？

**Comment by yann0917** [comment]
不兼容 calibre, 兼容多看，Mac books
