### ISSUE TITLE
下载的MarkDown文档按照时间排序，顺序和得到上的目录不一致怎么解决？

### ISSUE THREAD

**Issue by guochenchn** [yann0917/dedao-dl#241]
下载的markdown文档有的文档下载的时间戳是一样的，没法和得到上的目录一一对应

**Comment by yann0917** [comment]
下载最新代码，下载文档时添加 `-o` 参数即可

<img width="610" alt="image" src="https://github.com/user-attachments/assets/a155ca95-c589-488c-8827-ea9ffddd9184">

**Comment by guochenchn** [comment]
收到，感谢

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年11月28日 13:30 |
| 收件人 | yann0917/dedao-dl ***@***.***> |
| 抄送人 | guochenchn ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [yann0917/dedao-dl] 下载的MarkDown文档按照时间排序，顺序和得到上的目录不一致怎么解决？ (Issue #241) |

下载最新代码，下载文档时添加 -o 参数即可

image.png (view on web)
