### ISSUE TITLE
怎么直接下载罗辑思维,启发俱乐部所有内容

### ISSUE THREAD

**Issue by hcliu987** [yann0917/dedao-dl#33]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yann0917** [comment]
《罗辑思维·启发俱乐部》这个课程没有出现在已购买的课程列表里面，我抓一下数据看看。

**Comment by yann0917** [comment]
拉取最新代码，可以下载《罗辑思维·启发俱乐部》音频&pdf

**Comment by hcliu987** [comment]
![image](https://user-images.githubusercontent.com/52879991/122350077-78d5b600-cf7f-11eb-945c-85a073c219ff.png)
已更新最新， 获取已购买课程 报错

**Comment by yann0917** [comment]
> ![image](https://user-images.githubusercontent.com/52879991/122350077-78d5b600-cf7f-11eb-945c-85a073c219ff.png)
> 已更新最新， 获取已购买课程 报错

是不是没购买过任何课程？

**Comment by hcliu987** [comment]
和go 版本有问题吗，或者《罗辑思维·启发俱乐部》我的操作不对

**Comment by yann0917** [comment]
> 和go 版本有问题吗，或者《罗辑思维·启发俱乐部》我的操作不对

能不能把你的 cookies 发给我，我自己的测不出来这个问题。

**Comment by yann0917** [comment]
> 和go 版本有问题吗，或者《罗辑思维·启发俱乐部》我的操作不对

执行 `./deedao-dl cat` 看看统计信息，确定一下统计结果是不是有0的？

| # |   名称   | 统计 | 分类标签 |
|---|----------|------|----------|
| 0 | 全部     | 1833 | all      |
| 1 | 课程     |   71 | bauhinia |
| 2 | 听书书架 | 1475 | odob     |
| 3 | 电子书架 |  268 | ebook    |
| 4 | 锦囊     |   19 | compass  |

**Comment by hcliu987** [comment]
对，所有结果都是0

**Comment by hcliu987** [comment]
![image](https://user-images.githubusercontent.com/52879991/122523963-2ca37800-d04a-11eb-86ed-1247ef6e8089.png)
刚刚试了一下，确认查到结果全部是0

**Comment by yann0917** [comment]
> ![image](https://user-images.githubusercontent.com/52879991/122523963-2ca37800-d04a-11eb-86ed-1247ef6e8089.png)
> 刚刚试了一下，确认查到结果全部是0

bug 已修复

**Comment by hcliu987** [comment]
还是一样////算了。谢谢了
