### ISSUE TITLE
.cache 目录下文件打开失败

### ISSUE THREAD

**Issue by jxzzlfh** [yann0917/dedao-dl#43]
.cache 目录下文件打开失败，用记事本打开是乱码，这是怎么回事？

**Comment by jxzzlfh** [comment]
dedao-dl article -i xxx 查看课程文章信息，命令提交后，无反应，其余命令都没问题，我用的win10最新版

**Comment by yann0917** [comment]
> .cache 目录下文件打开失败，用记事本打开是乱码，这是怎么回事？

乱码是因为缓存的时候经过 `encoding/gob` 编码了，所以看到的是编码后的乱码。

**Comment by yann0917** [comment]
> dedao-dl article -i xxx 查看课程文章信息，命令提交后，无反应，其余命令都没问题，我用的win10最新版

-i 后面的参数是 课程 ID，如果是随便填的是没有任何信息的。

**Comment by newdhl** [comment]
之前用的win10，其他命令都行就是article报错，后来发现不能在.cache下生成articleList文件，所以dl命令也无法下载

今天改用win7，依旧无法生成articleList文件，但是前几天在win10上能运行的obod命令也无法使用了（win7 win10都不行了）提示：Error: 401 Unauthorized

**Comment by yann0917** [comment]
> 之前用的win10，其他命令都行就是article报错，后来发现不能在.cache下生成articleList文件，所以dl命令也无法下载
> 
> 今天改用win7，依旧无法生成articleList文件，但是前几天在win10上能运行的obod命令也无法使用了（win7 win10都不行了）提示：Error: 401 Unauthorized

授权失败是因为网页版登录过期了，需要重新登录拿到新的 cookie

**Comment by newdhl** [comment]
请问，什么时候更新window系统不需要articlelist  cache的版本？

**Comment by yann0917** [comment]
> 请问，什么时候更新window系统不需要articlelist cache的版本？

更新好了，另外最好别在已经 closed 的 issue 区提问，看不到提醒，有问题提 issue 就行。:smile:
