### ISSUE TITLE
go get失败

### ISSUE THREAD

**Issue by 578559967** [yann0917/dedao-dl#5]
go get失败，貌似依赖库的接口变了：
```shell
$ go get -u github.com/yann0917/dedao-dl
# github.com/yann0917/dedao-dl/utils
workspace/go/src/github.com/yann0917/dedao-dl/utils/chromedp.go:101:17: assignment mismatch: 2 variables but network.SetCookie(key, value).WithExpires(&expr).WithDomain(".dedao.cn").WithHTTPOnly(true).Do returns 1 values
workspace/go/src/github.com/yann0917/dedao-dl/utils/cookier.go:15:36: launcher.NewBrowser().LookPath undefined (type *launcher.Browser has no field or method LookPath)
```

**Comment by yann0917** [comment]
> go get失败，貌似依赖库的接口变了：
> 
> ```shell
> $ go get -u github.com/yann0917/dedao-dl
> # github.com/yann0917/dedao-dl/utils
> workspace/go/src/github.com/yann0917/dedao-dl/utils/chromedp.go:101:17: assignment mismatch: 2 variables but network.SetCookie(key, value).WithExpires(&expr).WithDomain(".dedao.cn").WithHTTPOnly(true).Do returns 1 values
> workspace/go/src/github.com/yann0917/dedao-dl/utils/cookier.go:15:36: launcher.NewBrowser().LookPath undefined (type *launcher.Browser has no field or method LookPath)
> ```

是的 [chromedp](github.com/chromedp/chromedp) 和 [rod](github.com/go-rod/rod) 接口改变了，已更新，请拉取最新代码。
