### ISSUE TITLE
导出PDF文件内容有遮挡，md 部分文件解析出错

### ISSUE THREAD

**Issue by newdhl** [yann0917/dedao-dl#64]
**Describe the bug**
1、Pdf文件会有banner在下方，挡住一部分文字，每一页都是如此，如
![image](https://user-images.githubusercontent.com/98757748/157449218-07cb85de-b0b2-4df4-84b9-2177a215140c.png)

2、311课程MD下载不了，mp3 pdf正常。提示如下

C:\Users\Y>dedao-dl dl 311 -t 3
正在生成文件：【[37;1m发刊词 | xxxxxx[0m】 [31;1m失败open output\XXX\MD/发刊词 | XXX.md: The filename, directory name, or volume label syntax is incorrect.[0m
Error: open output\XXX\MD/发刊词 | XXX.md: The filename, directory name, or volume label syntax is incorrect.
Usage:
  dedao-dl dl [flags]

**Comment by yann0917** [comment]
> **Describe the bug** 1、Pdf文件会有banner在下方，挡住一部分文字，每一页都是如此，如 ![image](https://user-images.githubusercontent.com/98757748/157449218-07cb85de-b0b2-4df4-84b9-2177a215140c.png)
> 
> 2、311课程MD下载不了，mp3 pdf正常。提示如下
> 
> C:\Users\Y>dedao-dl dl 311 -t 3 正在生成文件：【�[37;1m发刊词 | xxxxxx�[0m】 �[31;1m失败open output\XXX\MD/发刊词 | XXX.md: The filename, directory name, or volume label syntax is incorrect.�[0m Error: open output\XXX\MD/发刊词 | XXX.md: The filename, directory name, or volume label syntax is incorrect. Usage: dedao-dl dl [flags]

311 是什么课程，我没有这个课程，没法复现问题。

**Comment by newdhl** [comment]
311 是像证券交易员一样思考和行动


还有就是所有命令用在123课程上，都报错，在下载123课程之前，还成功下载过其他课程，提示如下：

C:\Users\Y>dedao-dl dl 123 -t 3                  *注 mp3 pdf md都是这个提示
err2: services.ArticleList.List: []services.ArticleIntro: services.ArticleIntro.Video: []services.Video: services.Video.ListenProgress: assertInteger: can not decode float as int, error found in #10 byte of ...|ogress":25.07,"liste|..., bigger context ...|1080_audio":"","is_drm":false,"listen_progress":25.07,"listen_finished":false,"log_id":"331723071514|...Error: services.ArticleList.List: []services.ArticleIntro: services.ArticleIntro.Video: []services.Video: services.Video.ListenProgress: assertInteger: can not decode float as int, error found in #10 byte of ...|ogress":25.07,"liste|..., bigger context ...|1080_audio":"","is_drm":false,"listen_progress":25.07,"listen_finished":false,"log_id":"331723071514|...
Usage:
  dedao-dl dl [flags]


C:\Users\Y>dedao-dl article -i 123
err2: services.ArticleList.List: []services.ArticleIntro: services.ArticleIntro.Video: []services.Video: services.Video.ListenProgress: assertInteger: can not decode float as int, error found in #10 byte of ...|ogress":25.07,"liste|..., bigger context ...|1080_audio":"","is_drm":false,"listen_progress":25.07,"listen_finished":false,"log_id":"331723071514|...Error: services.ArticleList.List: []services.ArticleIntro: services.ArticleIntro.Video: []services.Video: services.Video.ListenProgress: assertInteger: can not decode float as int, error found in #10 byte of ...|ogress":25.07,"liste|..., bigger context ...|1080_audio":"","is_drm":false,"listen_progress":25.07,"listen_finished":false,"log_id":"331723071514|...
Usage:
  dedao-dl article [flags]

**Comment by yann0917** [comment]
> 

学习进度怎么是小数，我这边都是整数，没发现这个问题。:cry:
